final version

diff --git a/.github/workflows/build-deploy.yaml b/.github/workflows/build-deploy.yaml
--- a/.github/workflows/build-deploy.yaml
+++ b/.github/workflows/build-deploy.yaml
@@ -114,11 +114,15 @@ jobs:
       - name: Terraform Import IAM Role (if exists)
         working-directory: ./terraform/envs/${{ github.event.inputs.environment }}
         run: |
+          set -e
           ROLE_NAME=lambda_exec_role-${{ github.event.inputs.environment }}
-          aws iam get-role --role-name $ROLE_NAME \
-          && terraform import module.iam.aws_iam_role.lambda_exec_role $ROLE_NAME \
-          || echo "IAM role not found, skipping import"
-
+    
+          if aws iam get-role --role-name "$ROLE_NAME"; then
+          echo "IAM Role $ROLE_NAME exists. Importing..."
+          terraform import module.iam.aws_iam_role.lambda_exec_role "$ROLE_NAME"
+          else
+          echo "IAM Role $ROLE_NAME not found. Skipping import."
+          fi
 
 
       - name: Terraform Import ECR (if exists)
